apiVersion: v1
kind: Service
metadata:
  name: openmrs
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
  selector:
    app: openmrs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs
spec:
  selector:
    matchLabels:
      app: openmrs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      containers:
      - image: openmrs/openmrs-reference-application-distro:2.8
        name: openmrs
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_DATABASE
          value: openmrs
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        - name: DB_CREATE_TABLES
          value: "true"
        ports:
        - containerPort: 8080
          name: openmrs
        volumeMounts:
        - name: openmrs-modules-storage
          mountPath: /usr/local/tomcat/.OpenMRS/modules
        - name: openmrs-owa-storage
          mountPath: /usr/local/tomcat/.OpenMRS/owa
      volumes:
      - name: openmrs-modules-storage
        persistentVolumeClaim:
          claimName: openmrs-modules-claim
      - name: openmrs-owa-storage
        persistentVolumeClaim:
          claimName: openmrs-owa-claim
